/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basedatosiii;

import javax.swing.JOptionPane;

/**
 *
 * @author GUSTAVO
 */
public class AdministrarUsuarios extends javax.swing.JFrame {

    AdministrarUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
        listaUsuarios.removeAll();
        Conexion.login = UserPassword.userOriginal;
        Conexion.password = UserPassword.passOriginal;
        Consulta.realizarConsultaLista("select username from all_users order by username", listaUsuarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRolesPrivilegios = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botNuevoUsuario = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList();
        botQuitarRolPriv = new javax.swing.JButton();
        panelNuevoPriv = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaRolesPrivAgregar = new javax.swing.JList();
        botonAgregarRolPrivilegio = new javax.swing.JButton();
        botEliminarUsuario = new javax.swing.JButton();
        botonConectarse = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRAR USUARIOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRAR USUARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, -1));

        listaRolesPrivilegios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaRolesPrivilegiosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaRolesPrivilegios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 410, 190));

        jLabel3.setText("Roles y privilegios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel4.setText("Usuarios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        botNuevoUsuario.setText("Nuevo usuario");
        botNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botNuevoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 150, -1));

        listaUsuarios.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " ", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaUsuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaUsuariosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaUsuarios);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 340, 150));

        botQuitarRolPriv.setText("Quitar rol o privilegio");
        botQuitarRolPriv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botQuitarRolPrivActionPerformed(evt);
            }
        });
        getContentPane().add(botQuitarRolPriv, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 160, -1));

        panelNuevoPriv.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar rol o privilegio"));
        panelNuevoPriv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaRolesPrivAgregar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaRolesPrivAgregarValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaRolesPrivAgregar);

        panelNuevoPriv.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 21, -1, 190));

        botonAgregarRolPrivilegio.setText("Agregar rol o privilegio");
        botonAgregarRolPrivilegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarRolPrivilegioActionPerformed(evt);
            }
        });
        panelNuevoPriv.add(botonAgregarRolPrivilegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        getContentPane().add(panelNuevoPriv, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 370, 260));

        botEliminarUsuario.setText("Eliminar usuario");
        botEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEliminarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 150, -1));

        botonConectarse.setText("Conectarse");
        botonConectarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConectarseActionPerformed(evt);
            }
        });
        getContentPane().add(botonConectarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 110, -1));

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaUsuariosValueChanged
        listaUsuarios.removeAll();
        Consulta.realizarConsultaLista(consultaPrivsUsuarios1 + listaUsuarios.getSelectedValue() + consultaPrivsUsuarios2, listaRolesPrivilegios);
        Consulta.realizarConsultaLista("select distinct privilege from role_sys_privs "
                + "union select distinct grantee from dba_sys_privs", listaRolesPrivAgregar);
    }//GEN-LAST:event_listaUsuariosValueChanged

    private void listaRolesPrivilegiosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaRolesPrivilegiosValueChanged

    }//GEN-LAST:event_listaRolesPrivilegiosValueChanged

    private void botQuitarRolPrivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botQuitarRolPrivActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "Esta seguro de revocar este rol o privilegio", "REVOCAR ROL O PRIVILEGIO", 2);
        if (opcion == 0) {
            Consulta.realizarConsulta("revoke " + listaRolesPrivilegios.getSelectedValue() + " from " + listaUsuarios.getSelectedValue());
            Consulta.realizarConsultaLista(consultaPrivsUsuarios1 + listaUsuarios.getSelectedValue() + consultaPrivsUsuarios2, listaRolesPrivilegios);
            Consulta.realizarConsultaLista("select distinct privilege from role_sys_privs "
                    + "union select distinct grantee from dba_sys_privs", listaRolesPrivAgregar);
        }

    }//GEN-LAST:event_botQuitarRolPrivActionPerformed

    private void listaRolesPrivAgregarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaRolesPrivAgregarValueChanged

    }//GEN-LAST:event_listaRolesPrivAgregarValueChanged

    private void botonAgregarRolPrivilegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarRolPrivilegioActionPerformed
        Consulta.realizarConsulta("grant " + listaRolesPrivAgregar.getSelectedValue() + " to " + listaUsuarios.getSelectedValue());
        Consulta.realizarConsultaLista(consultaPrivsUsuarios1 + listaUsuarios.getSelectedValue() + consultaPrivsUsuarios2, listaRolesPrivilegios);
        Consulta.realizarConsultaLista("select distinct privilege from role_sys_privs "
                + "union select distinct grantee from dba_sys_privs", listaRolesPrivAgregar);
    }//GEN-LAST:event_botonAgregarRolPrivilegioActionPerformed

    private void botNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botNuevoUsuarioActionPerformed
        String nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre del nuevo usuario", "NUEVO USUARIO", 3);
        String pass = JOptionPane.showInputDialog(null, "Ingrese la contraseña del nuevo usuario", "NUEVO USUARIO", 3);
        if (!nombre.trim().equals("") && !pass.trim().equals("")) {
            Consulta.realizarConsulta("create user " + nombre + " identified by " + pass);
            Consulta.realizarConsultaLista(consultaPrivsUsuarios1 + listaUsuarios.getSelectedValue() + consultaPrivsUsuarios2, listaRolesPrivilegios);
            Consulta.realizarConsultaLista("select distinct privilege from role_sys_privs "
                    + "union select distinct grantee from dba_sys_privs", listaRolesPrivAgregar);
            Consulta.realizarConsultaLista("select username from all_users order by username", listaUsuarios);
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar un nombre y contraseña para el nuevo usuario", "ERROR", 0);
        }
    }//GEN-LAST:event_botNuevoUsuarioActionPerformed

    private void botEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEliminarUsuarioActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar este usuario", "ELIMINAR ROL", 2);
        if (opcion == 0) {
            Consulta.realizarConsulta("drop user " + listaUsuarios.getSelectedValue());
            Consulta.realizarConsultaLista(consultaPrivsUsuarios1 + listaUsuarios.getSelectedValue() + consultaPrivsUsuarios2, listaRolesPrivilegios);
            Consulta.realizarConsultaLista("select distinct privilege from role_sys_privs "
                    + "union select distinct grantee from dba_sys_privs", listaRolesPrivAgregar);
            Consulta.realizarConsultaLista("select username from all_users order by username", listaUsuarios);
        }
    }//GEN-LAST:event_botEliminarUsuarioActionPerformed

    private void botonConectarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConectarseActionPerformed
        String cont = JOptionPane.showInputDialog(null, "Ingrese la contraseña del usuario " + listaUsuarios.getSelectedValue(), "CONECTARSE", 3);
        Conexion.login = String.valueOf(listaUsuarios.getSelectedValue());
        Conexion.password = cont;
        Esquema ae = new Esquema(String.valueOf(listaUsuarios.getSelectedValue()));
        dispose();
        ae.setVisible(true);
    }//GEN-LAST:event_botonConectarseActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        Administrador ad = new Administrador();
        dispose();
        ad.setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botEliminarUsuario;
    private javax.swing.JToggleButton botNuevoUsuario;
    private javax.swing.JButton botQuitarRolPriv;
    private javax.swing.JButton botonAgregarRolPrivilegio;
    private javax.swing.JButton botonConectarse;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaRolesPrivAgregar;
    private javax.swing.JList listaRolesPrivilegios;
    private javax.swing.JList listaUsuarios;
    private javax.swing.JPanel panelNuevoPriv;
    // End of variables declaration//GEN-END:variables

    private final String consultaPrivsUsuarios1 = "select\n"
            + "  lpad(' ', 2*level) || granted_role\n"
            + "from\n"
            + "  (\n"
            + "  /* THE USERS */\n"
            + "    select \n"
            + "      null     grantee, \n"
            + "      username granted_role\n"
            + "    from \n"
            + "      dba_users\n"
            + "    where\n"
            + "      username like upper('%";
    private final String consultaPrivsUsuarios2 = "%')\n"
            + "  /* THE ROLES TO ROLES RELATIONS */ \n"
            + "  union\n"
            + "    select \n"
            + "      grantee,\n"
            + "      granted_role\n"
            + "    from\n"
            + "      dba_role_privs\n"
            + "  /* THE ROLES TO PRIVILEGE RELATIONS */ \n"
            + "  union\n"
            + "    select\n"
            + "      grantee,\n"
            + "      privilege\n"
            + "    from\n"
            + "      dba_sys_privs\n"
            + "  )\n"
            + "start with grantee is null\n"
            + "connect by grantee = prior granted_role";
}
