/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AgregarRutas.java
 *
 * Created on 08/07/2011, 08:59:37 PM
 */

package interfazGraficaAgregar;

import excepciones.FachadaException;
import fachadas.ListadoRutas;
import fachadas.ListadoUbicaciones;
import fachadas.ListadoUnidades;
import interfaces.IFachadaRuta;
import interfazGrafica.Menu;
import java.util.Vector;
import javax.swing.JOptionPane;
import objetoProyecto.Ruta;
import objetoProyecto.Ubicacion;
import objetoProyecto.Unidad;
import objetoServicio.Fecha;
import objetoServicio.NumeroFloat;
import objetoServicio.NumeroInt;
import interfazGraficaModificar.*;
import interfazGraficaEliminar.*;
import interfazGraficaTablas.*;

/**
 *
 * @author Gustavo
 */
public class AgregarRutas extends javax.swing.JFrame {

    /** Creates new form AgregarRutas */
    public AgregarRutas() {
        initComponents();
        setLocationRelativeTo(null);
    }
private ListadoUbicaciones listaUbicaciones=new ListadoUbicaciones();
private ListadoUnidades listaUnidades=new ListadoUnidades();
private ListadoRutas listaRutas=new ListadoRutas();
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        tiempoAproximado = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        costo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        horaViaje = new javax.swing.JTextField();
        distancia = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        lugarSalida = new javax.swing.JComboBox();
        lugarLlegada = new javax.swing.JComboBox();
        unidad = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        agre_ubi = new javax.swing.JMenuItem();
        mod_udi = new javax.swing.JMenuItem();
        eli_ubi = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        agre_unid = new javax.swing.JMenuItem();
        mod_unid = new javax.swing.JMenuItem();
        elim_unid = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        con_ubi = new javax.swing.JMenuItem();
        con_uni = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cooperativa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("AGREGAR RUTA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 11, -1, -1));

        jLabel2.setText("Código ruta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, -1));

        jLabel3.setText("Lugar salida:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, -1));

        jLabel4.setText("Lugar llegada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        jLabel5.setText("Tiempo aproximado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel6.setText("Costo ruta:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setText("Hora:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel8.setText("Distancia:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel9.setText("Unidad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel10.setText("Fecha:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 97, -1));

        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        tiempoAproximado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiempoAproximadoKeyTyped(evt);
            }
        });
        getContentPane().add(tiempoAproximado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 141, 99, -1));
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 43, 79, -1));

        costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costoKeyTyped(evt);
            }
        });
        getContentPane().add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 99, -1));

        jLabel11.setText("dd/mm/aaaa");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 110, -1));

        horaViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaViajeActionPerformed(evt);
            }
        });
        horaViaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horaViajeKeyTyped(evt);
            }
        });
        getContentPane().add(horaViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, -1));

        distancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanciaActionPerformed(evt);
            }
        });
        distancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                distanciaKeyTyped(evt);
            }
        });
        getContentPane().add(distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 90, -1));

        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });
        dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diaKeyTyped(evt);
            }
        });
        getContentPane().add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 30, -1));

        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });
        mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesKeyTyped(evt);
            }
        });
        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 40, -1));

        año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoActionPerformed(evt);
            }
        });
        año.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                añoKeyTyped(evt);
            }
        });
        getContentPane().add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 60, -1));

        jLabel13.setText("hh.mm");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 80, -1));

        jLabel14.setText("/");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 10, -1));

        jLabel15.setText("KM");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 60, -1));

        jLabel16.setText("/");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 10, -1));

        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        lugarSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lugarSalidaMouseClicked(evt);
            }
        });
        lugarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(lugarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 320, -1));

        getContentPane().add(lugarLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 320, -1));

        unidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unidadItemStateChanged(evt);
            }
        });
        getContentPane().add(unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 140, -1));

        jLabel17.setText("$");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 40, -1));

        jLabel18.setText("horas");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 80, -1));

        jMenu1.setText("Agregar");

        jMenu3.setText("Ubicacion");

        agre_ubi.setText("Agregar");
        agre_ubi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agre_ubiActionPerformed(evt);
            }
        });
        jMenu3.add(agre_ubi);

        mod_udi.setText("Modificar");
        mod_udi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_udiActionPerformed(evt);
            }
        });
        jMenu3.add(mod_udi);

        eli_ubi.setText("Eliminar");
        eli_ubi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eli_ubiActionPerformed(evt);
            }
        });
        jMenu3.add(eli_ubi);

        jMenu1.add(jMenu3);

        jMenu4.setText("Unidad");

        agre_unid.setText("Agregar");
        agre_unid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agre_unidActionPerformed(evt);
            }
        });
        jMenu4.add(agre_unid);

        mod_unid.setText("Modificar");
        mod_unid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_unidActionPerformed(evt);
            }
        });
        jMenu4.add(mod_unid);

        elim_unid.setText("Eliminar");
        elim_unid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elim_unidActionPerformed(evt);
            }
        });
        jMenu4.add(elim_unid);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        con_ubi.setText("Ubicacion");
        con_ubi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_ubiActionPerformed(evt);
            }
        });
        jMenu2.add(con_ubi);

        con_uni.setText("Unidad");
        con_uni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_uniActionPerformed(evt);
            }
        });
        jMenu2.add(con_uni);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Vector lista = new Vector();
        try {
            lista = listaUbicaciones.consultaUbicaciones();

        } catch (FachadaException fe) {
            JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
        }
        for (int i = 0; i < lista.size(); i++){
            Ubicacion c = (Ubicacion) lista.get(i);
            lugarSalida.addItem(c.getNombreUbicacion());
            lugarLlegada.addItem(c.getNombreUbicacion());
        }
        Vector lista2 = new Vector();
        try {
            lista2 = listaUnidades.consultaUnidades();
        } catch (FachadaException fe) {
            JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
        }
        for (int i = 0; i < lista2.size(); i++){
            Unidad c = (Unidad) lista2.get(i);
            unidad.addItem(c.getCodigoUnidad());
        }
    }//GEN-LAST:event_formWindowOpened

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        Menu me=new Menu();
        dispose();
        me.setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    private void tiempoAproximadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiempoAproximadoKeyTyped
        // TODO add your handling code here:
        NumeroFloat.Validar(evt);
    NumeroFloat.numeroCaracteres(tiempoAproximado,5, evt);
    }//GEN-LAST:event_tiempoAproximadoKeyTyped

    private void horaViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaViajeActionPerformed

    private void distanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distanciaActionPerformed

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesActionPerformed

    private void añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añoActionPerformed

    private void costoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoKeyTyped
        // TODO add your handling code here:
        NumeroFloat.Validar(evt);
    NumeroFloat.numeroCaracteres(costo,5, evt);
    }//GEN-LAST:event_costoKeyTyped

    private void horaViajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horaViajeKeyTyped
        // TODO add your handling code here:
        NumeroFloat.Validar(evt);
    NumeroFloat.numeroCaracteres(costo,5, evt);
    }//GEN-LAST:event_horaViajeKeyTyped

    private void distanciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_distanciaKeyTyped
        // TODO add your handling code here:
        NumeroFloat.Validar(evt);
    NumeroFloat.numeroCaracteres(distancia,6, evt);
    }//GEN-LAST:event_distanciaKeyTyped

    private void diaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaKeyTyped
        // TODO add your handling code here:
        NumeroInt.Validar(evt);
    NumeroInt.numeroCaracteres(dia, 2, evt);
    }//GEN-LAST:event_diaKeyTyped

    private void mesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesKeyTyped
        // TODO add your handling code here:
        NumeroInt.Validar(evt);
    NumeroInt.numeroCaracteres(mes, 2, evt);
    }//GEN-LAST:event_mesKeyTyped

    private void añoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_añoKeyTyped
        // TODO add your handling code here:
        NumeroInt.Validar(evt);
    NumeroInt.numeroCaracteres(año, 4, evt);
    }//GEN-LAST:event_añoKeyTyped

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        codigo.setText("");
        tiempoAproximado.setText("");
        costo.setText("");
        horaViaje.setText("");
        distancia.setText("");
        dia.setText("");
        mes.setText("");
        año.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        if(codigo.getText().equals("")||tiempoAproximado.getText().equals("")
                ||costo.getText().equals("")||horaViaje.getText().equals("")
                ||dia.getText().equals("")||mes.getText().equals("")
                ||año.getText().equals("")||distancia.getText().equals("")||
                lugarLlegada.getSelectedIndex()==lugarSalida.getSelectedIndex()
                ||unidad.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null,"Se encontró un error en alguno de los campos");
        }
 else{
            Vector lista=new Vector();
            try {
            lista=listaRutas.consultaUnidadRuta((String)unidad.getSelectedItem());
        } catch (FachadaException fe) {
            JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
        }
            if(lista.isEmpty()){
                Ruta ruta =new Ruta();
            ruta.setCodigoRuta(codigo.getText());
            ruta.setCostoRuta(Float.parseFloat(costo.getText()));
            ruta.setDistancia(Float.parseFloat(distancia.getText()));
            Fecha fecha=new Fecha();
            fecha.setDia(Integer.parseInt(dia.getText()));
            fecha.setMes(Integer.parseInt(mes.getText()));
            fecha.setAño(Integer.parseInt(año.getText()));
            ruta.setFecha(fecha);
            ruta.setHora(Float.parseFloat(horaViaje.getText()));
            ruta.setLugarLlegada((String)lugarLlegada.getSelectedItem());
            ruta.setLugarSalida((String)lugarSalida.getSelectedItem());
            ruta.setUnidad((String)unidad.getSelectedItem());
            ruta.setTiempoAproximado(Float.parseFloat(tiempoAproximado.getText()));

            IFachadaRuta rutas=new ListadoRutas();
            try{
                rutas.agrega(ruta);
                    JOptionPane.showMessageDialog(null, "Ruta guardada con éxito" );
                    AgregarRutas me=new AgregarRutas();
                    dispose();
                    me.setVisible(true);
            }catch(FachadaException fe){
                JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
            }
            }
 else{
                JOptionPane.showMessageDialog(null,"Error: La unidad ya está designada a otra ruta");
 }
}
 
    }//GEN-LAST:event_guardarActionPerformed

    private void lugarSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lugarSalidaMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_lugarSalidaMouseClicked

    private void agre_ubiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agre_ubiActionPerformed
        // TODO add your handling code here:

        AgregarUbicaciones b= new AgregarUbicaciones();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_agre_ubiActionPerformed

    private void mod_udiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_udiActionPerformed
        // TODO add your handling code here:
        ModificarUbicaciones vv = new ModificarUbicaciones();
        vv.setVisible(true);
        dispose();
    }//GEN-LAST:event_mod_udiActionPerformed

    private void eli_ubiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eli_ubiActionPerformed
        // TODO add your handling code here:
        EliminarUbicaciones jj = new EliminarUbicaciones();
        jj.setVisible(true);
        dispose();
    }//GEN-LAST:event_eli_ubiActionPerformed

    private void agre_unidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agre_unidActionPerformed
        // TODO add your handling code here:
        AgregarUnidades gg = new AgregarUnidades();
        gg.setVisible(true);
        dispose();
    }//GEN-LAST:event_agre_unidActionPerformed

    private void mod_unidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_unidActionPerformed
        // TODO add your handling code here:
        ModificarUnidades vv = new ModificarUnidades();
        vv.setVisible(true);
        dispose();
    }//GEN-LAST:event_mod_unidActionPerformed

    private void elim_unidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elim_unidActionPerformed
        // TODO add your handling code here:
        EliminarUnidades bb = new EliminarUnidades();
        bb.setVisible(true);
        dispose();
    }//GEN-LAST:event_elim_unidActionPerformed

    private void con_ubiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_ubiActionPerformed
        // TODO add your handling code here:
        TablaUbicaciones gg = new TablaUbicaciones();
        gg.setVisible(true);
        dispose();
    }//GEN-LAST:event_con_ubiActionPerformed

    private void con_uniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_uniActionPerformed
        // TODO add your handling code here:
        TablaUnidades re = new TablaUnidades();
        re.setVisible(true);
        dispose();
    }//GEN-LAST:event_con_uniActionPerformed

    private void lugarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lugarSalidaActionPerformed

    private void unidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_unidadItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agre_ubi;
    private javax.swing.JMenuItem agre_unid;
    private javax.swing.JTextField año;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigo;
    private javax.swing.JMenuItem con_ubi;
    private javax.swing.JMenuItem con_uni;
    private javax.swing.JTextField costo;
    private javax.swing.JTextField dia;
    private javax.swing.JTextField distancia;
    private javax.swing.JMenuItem eli_ubi;
    private javax.swing.JMenuItem elim_unid;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField horaViaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton limpiar;
    private javax.swing.JComboBox lugarLlegada;
    private javax.swing.JComboBox lugarSalida;
    private javax.swing.JTextField mes;
    private javax.swing.JMenuItem mod_udi;
    private javax.swing.JMenuItem mod_unid;
    private javax.swing.JTextField tiempoAproximado;
    private javax.swing.JComboBox unidad;
    // End of variables declaration//GEN-END:variables

}
