/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModificarRutas.java
 *
 * Created on 10/07/2011, 11:40:55 AM
 */

package interfazGraficaModificar;

import excepciones.FachadaException;
import fachadas.ListadoRutas;
import fachadas.ListadoUbicaciones;
import fachadas.ListadoUnidades;
import interfazGrafica.Menu;
import java.util.Vector;
import javax.swing.JOptionPane;
import objetoProyecto.Ruta;
import objetoProyecto.Ubicacion;
import objetoProyecto.Unidad;
import objetoServicio.Fecha;
import objetoServicio.NumeroFloat;
import objetoServicio.NumeroInt;

/**
 *
 * @author Gustavo
 */
public class ModificarRutas extends javax.swing.JFrame {

    /** Creates new form ModificarRutas */
    public ModificarRutas() {
        initComponents();
        setLocationRelativeTo(null);
    }
    private Ruta buscado;
    private ListadoRutas listaRutas=new ListadoRutas();
    private ListadoUbicaciones listaUbicaciones=new ListadoUbicaciones();
    private ListadoUnidades listaUnidades=new ListadoUnidades();
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        tiempoAproximado = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        costo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        horaViaje = new javax.swing.JTextField();
        distancia = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        llegadaActual = new javax.swing.JTextField();
        salidaActual = new javax.swing.JTextField();
        unidadActual = new javax.swing.JTextField();
        lugarSalida = new javax.swing.JComboBox();
        lugarLlegada = new javax.swing.JComboBox();
        unidad = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cooperativa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MODIFICAR RUTAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 11, -1, -1));

        jLabel2.setText("Código ruta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, -1));

        jLabel3.setText("Lugar salida:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, -1));

        jLabel4.setText("Lugar llegada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        jLabel5.setText("Tiempo aproximado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel6.setText("Costo ruta:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setText("Hora:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel8.setText("Distancia:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel9.setText("Unidad:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel10.setText("Fecha:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 97, -1));

        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        tiempoAproximado.setEnabled(false);
        tiempoAproximado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiempoAproximadoKeyTyped(evt);
            }
        });
        getContentPane().add(tiempoAproximado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 99, -1));
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 43, 79, -1));

        costo.setEnabled(false);
        costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costoKeyTyped(evt);
            }
        });
        getContentPane().add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 99, -1));

        jLabel11.setText("dd/mm/aaaa");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 80, -1));

        horaViaje.setEnabled(false);
        horaViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaViajeActionPerformed(evt);
            }
        });
        horaViaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                horaViajeKeyTyped(evt);
            }
        });
        getContentPane().add(horaViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, -1));

        distancia.setEnabled(false);
        distancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanciaActionPerformed(evt);
            }
        });
        distancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                distanciaKeyTyped(evt);
            }
        });
        getContentPane().add(distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 90, -1));

        dia.setEnabled(false);
        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });
        dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diaKeyTyped(evt);
            }
        });
        getContentPane().add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 30, -1));

        mes.setEnabled(false);
        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });
        mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesKeyTyped(evt);
            }
        });
        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 40, -1));

        año.setEnabled(false);
        año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoActionPerformed(evt);
            }
        });
        año.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                añoKeyTyped(evt);
            }
        });
        getContentPane().add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 60, -1));

        jLabel13.setText("hh.mm");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 60, -1));

        jLabel14.setText("/");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 10, -1));

        jLabel15.setText("KM");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 30, -1));

        jLabel16.setText("/");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 10, -1));

        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 43, -1, -1));

        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        llegadaActual.setEnabled(false);
        llegadaActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                llegadaActualKeyTyped(evt);
            }
        });
        getContentPane().add(llegadaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, -1));

        salidaActual.setEnabled(false);
        salidaActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salidaActualKeyTyped(evt);
            }
        });
        getContentPane().add(salidaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 100, -1));

        unidadActual.setEnabled(false);
        unidadActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unidadActualKeyTyped(evt);
            }
        });
        getContentPane().add(unidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 50, -1));

        getContentPane().add(lugarSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 320, -1));

        getContentPane().add(lugarLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 320, -1));

        getContentPane().add(unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 70, -1));

        jLabel17.setText("Actual");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jLabel18.setText("Actual");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        Menu me=new Menu();
        dispose();
        me.setVisible(true);
}//GEN-LAST:event_cancelarActionPerformed

    private void tiempoAproximadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiempoAproximadoKeyTyped
        // TODO add your handling code here:
        NumeroFloat.Validar(evt);
        NumeroFloat.numeroCaracteres(tiempoAproximado,5, evt);
}//GEN-LAST:event_tiempoAproximadoKeyTyped

    private void costoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoKeyTyped
        // TODO add your handling code here:
        NumeroFloat.Validar(evt);
        NumeroFloat.numeroCaracteres(costo,5, evt);
}//GEN-LAST:event_costoKeyTyped

    private void horaViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaViajeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_horaViajeActionPerformed

    private void horaViajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horaViajeKeyTyped
        // TODO add your handling code here:
        NumeroInt.Validar(evt);
        NumeroInt.numeroCaracteres(horaViaje, 2, evt);
}//GEN-LAST:event_horaViajeKeyTyped

    private void distanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanciaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_distanciaActionPerformed

    private void distanciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_distanciaKeyTyped
        // TODO add your handling code here:
        NumeroFloat.Validar(evt);
        NumeroFloat.numeroCaracteres(distancia,6, evt);
}//GEN-LAST:event_distanciaKeyTyped

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_diaActionPerformed

    private void diaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaKeyTyped
        // TODO add your handling code here:
        NumeroInt.Validar(evt);
        NumeroInt.numeroCaracteres(dia, 2, evt);
}//GEN-LAST:event_diaKeyTyped

    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_mesActionPerformed

    private void mesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesKeyTyped
        // TODO add your handling code here:
        NumeroInt.Validar(evt);
        NumeroInt.numeroCaracteres(mes, 2, evt);
}//GEN-LAST:event_mesKeyTyped

    private void añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_añoActionPerformed

    private void añoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_añoKeyTyped
        // TODO add your handling code here:
        NumeroInt.Validar(evt);
        NumeroInt.numeroCaracteres(año, 4, evt);
}//GEN-LAST:event_añoKeyTyped

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        tiempoAproximado.setText("");
        costo.setText("");
        horaViaje.setText("");
        distancia.setText("");
        dia.setText("");
        mes.setText("");
        año.setText("");
}//GEN-LAST:event_limpiarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        unidadActual.setText("");
        llegadaActual.setText("");
        salidaActual.setText("");
        tiempoAproximado.setText("");
        costo.setText("");
        horaViaje.setText("");
        distancia.setText("");
        dia.setText("");
        mes.setText("");
        año.setText("");
        buscado=null;
        if(!codigo.getText().equals("")){
            Ruta ruta=new Ruta();
            ruta.setCodigoRuta(codigo.getText());
            try{
                buscado=listaRutas.obten(ruta);
            }catch(FachadaException fe){
                JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
            }
            if(buscado!=null){
                salidaActual.setText(buscado.getLugarSalida());
                llegadaActual.setText(buscado.getLugarLlegada());
                unidadActual.setText(buscado.getUnidad());
                tiempoAproximado.setText(String.valueOf(buscado.getTiempoAproximado()));
                costo.setText(String.valueOf(buscado.getCostoRuta()));
                horaViaje.setText(String.valueOf(buscado.getHora()));
                dia.setText(String.valueOf(buscado.getFecha().getDia()));
                mes.setText(String.valueOf(buscado.getFecha().getMes()));
                año.setText(String.valueOf(buscado.getFecha().getAño()));
                distancia.setText(String.valueOf(buscado.getDistancia()));

                lugarSalida.setEnabled(true);
                lugarLlegada.setEnabled(true);
                tiempoAproximado.setEnabled(true);
                costo.setEnabled(true);
                horaViaje.setEnabled(true);
                dia.setEnabled(true);
                mes.setEnabled(true);
                año.setEnabled(true);
                distancia.setEnabled(true);
                unidad.setEnabled(true);
            }
 else{
                JOptionPane.showMessageDialog(null, "La ruta no existe");
                lugarSalida.setEnabled(false);
                lugarLlegada.setEnabled(false);
                tiempoAproximado.setEnabled(false);
                costo.setEnabled(false);
                horaViaje.setEnabled(false);
                dia.setEnabled(false);
                mes.setEnabled(false);
                año.setEnabled(false);
                distancia.setEnabled(false);
                unidad.setEnabled(false);
 }
        }
 else{
            JOptionPane.showMessageDialog(null,"Ingrese el código de la unidad");
 }
    }//GEN-LAST:event_buscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Vector lista = new Vector();
        try {
            lista = listaUbicaciones.consultaUbicaciones();

        } catch (FachadaException fe) {
            JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
        }
        for (int i = 0; i < lista.size(); i++){
            Ubicacion c = (Ubicacion) lista.get(i);
            lugarSalida.addItem(c.getNombreUbicacion());
            lugarLlegada.addItem(c.getNombreUbicacion());
        }
        Vector lista2 = new Vector();
        try {
            lista2 = listaUnidades.consultaUnidades();
        } catch (FachadaException fe) {
            JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
        }
        for (int i = 0; i < lista2.size(); i++){
            Unidad c = (Unidad) lista2.get(i);
            unidad.addItem(c.getCodigoUnidad());
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        if(codigo.getText().equals("")||tiempoAproximado.getText().equals("")
                ||costo.getText().equals("")||horaViaje.getText().equals("")
                ||distancia.getText().equals("")
                ||dia.getText().equals("")||mes.getText().equals("")
                ||año.getText().equals("")||lugarLlegada.getSelectedIndex()==lugarSalida.getSelectedIndex()){
            JOptionPane.showMessageDialog(null,"Se encontró un error en alguno de los campos");
        }
 else{
            if(buscado!=null){
                Vector lista=new Vector();
            try {
            lista=listaRutas.consultaUnidadRuta((String)unidad.getSelectedItem());
        } catch (FachadaException fe) {
            JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
        }
                if(unidadActual.getText().equals((String)unidad.getSelectedItem())
                        ||lista.isEmpty()){
                buscado.setCostoRuta(Float.parseFloat(costo.getText()));
                buscado.setDistancia(Float.parseFloat(distancia.getText()));
                Fecha fecha=new Fecha();
                fecha.setDia(Integer.parseInt(dia.getText()));
                fecha.setMes(Integer.parseInt(mes.getText()));
                fecha.setAño(Integer.parseInt(año.getText()));
                buscado.setFecha(fecha);
                buscado.setHora(Float.parseFloat(horaViaje.getText()));
                buscado.setLugarLlegada((String)lugarLlegada.getSelectedItem());
                buscado.setLugarSalida((String)lugarSalida.getSelectedItem());
                buscado.setTiempoAproximado(Float.parseFloat(tiempoAproximado.getText()));
                buscado.setUnidad((String)unidad.getSelectedItem());
                try {
                listaRutas.actualiza(buscado);
                JOptionPane.showMessageDialog(null,"Ruta modificada con éxito");
                Menu me=new Menu();
        dispose();
        me.setVisible(true);
            } catch (FachadaException fe) {
                JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
            }
            }
                else{
                JOptionPane.showMessageDialog(null,"La unidad ya está designada a otra ruta");
 }
            }
 }
    }//GEN-LAST:event_modificarActionPerformed

    private void llegadaActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_llegadaActualKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_llegadaActualKeyTyped

    private void salidaActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salidaActualKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_salidaActualKeyTyped

    private void unidadActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadActualKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadActualKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField año;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField costo;
    private javax.swing.JTextField dia;
    private javax.swing.JTextField distancia;
    private javax.swing.JTextField horaViaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField llegadaActual;
    private javax.swing.JComboBox lugarLlegada;
    private javax.swing.JComboBox lugarSalida;
    private javax.swing.JTextField mes;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField salidaActual;
    private javax.swing.JTextField tiempoAproximado;
    private javax.swing.JComboBox unidad;
    private javax.swing.JTextField unidadActual;
    // End of variables declaration//GEN-END:variables

}
