/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModificarUbicaciones.java
 *
 * Created on 09/07/2011, 07:29:29 PM
 */

package interfazGraficaModificar;

import excepciones.FachadaException;
import fachadas.ListadoRutas;
import fachadas.ListadoUbicaciones;
import interfazGraficaAgregar.AgregarRutas;
import java.util.Vector;
import javax.swing.JOptionPane;
import objetoProyecto.Ubicacion;

/**
 *
 * @author Gustavo
 */
public class ModificarUbicaciones extends javax.swing.JFrame {

    /** Creates new form ModificarUbicaciones */
    public ModificarUbicaciones() {
        initComponents();
        setLocationRelativeTo(null);
    }
    private ListadoUbicaciones listaUbicaciones=new ListadoUbicaciones();
    private ListadoRutas listaRutas=new ListadoRutas();
private Ubicacion buscado;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        nombreUbicacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cooperativa");

        jLabel2.setText("Código ubicacón:");

        jLabel3.setText("Nombre ubicación:");

        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jLabel1.setText("MODIFICAR UBICACIONES");

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        nombreUbicacion.setEnabled(false);
        nombreUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUbicacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nombreUbicacion)
                                            .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(limpiar, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(modificar))
                                .addGap(29, 29, 29)
                                .addComponent(buscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar)
                    .addComponent(limpiar))
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        codigo.setText("");
        nombreUbicacion.setText("");

}//GEN-LAST:event_limpiarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        AgregarRutas me=new AgregarRutas();
        dispose();
        me.setVisible(true);
}//GEN-LAST:event_cancelarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
        if(codigo.getText().equals("")||nombreUbicacion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos" );
            }else{
        if(buscado!=null){
            buscado.setNombreUbicacion(nombreUbicacion.getText());
            Vector lista1=new Vector();
                try{
                lista1=listaRutas.consultaLugarSalida(buscado.getCodigoUbicacon());
                }catch(FachadaException fe){
                    JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
                }
            Vector lista2=new Vector();
                try{
                lista2=listaRutas.consultaLugarLlegada(buscado.getCodigoUbicacon());
                }catch(FachadaException fe){
                    JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
                }
            if(lista1.isEmpty()&&lista2.isEmpty()){
            try {
                listaUbicaciones.actualiza(buscado);
                JOptionPane.showMessageDialog(null,"Ubicación modificada con éxito");
                AgregarRutas me=new AgregarRutas();
        dispose();
        me.setVisible(true);
            } catch (FachadaException fe) {
                JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
            }
        }
            else{
                JOptionPane.showMessageDialog(null, "Error: La ubiación es utilizada en una ruta");
 }
        }
        }
        
}//GEN-LAST:event_modificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        nombreUbicacion.setText("");
        buscado=null;
        if(!codigo.getText().equals("")){
            Ubicacion ubicacion=new Ubicacion();
            ubicacion.setCodigoUbicacon(codigo.getText());
            try{
                buscado=listaUbicaciones.obten(ubicacion);
            }catch(FachadaException fe){
                JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
            }
            if(buscado!=null){
                nombreUbicacion.setText(buscado.getNombreUbicacion());

                nombreUbicacion.setEnabled(true);
            }
 else{
                JOptionPane.showMessageDialog(null,"La ubicación no existe");
                nombreUbicacion.setEnabled(false);
 }
        }
 else{
            JOptionPane.showMessageDialog(null,"Ingrese el código de la ubicación");
 }
    }//GEN-LAST:event_buscarActionPerformed

    private void nombreUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUbicacionActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nombreUbicacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombreUbicacion;
    // End of variables declaration//GEN-END:variables

}
