/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Inicio.java
 *
 * Created on 19/04/2013, 10:34:05 AM
 */
package analisisNumerico;

/**
 *
 * @author gustavo
 */
public class Inicio extends javax.swing.JFrame {

    /** Creates new form Inicio */
    public static int posArchivo;
    public static double vecArchivo[];
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        vecArchivo=Metodos.leerArchivo();//llena el vector con los elementos del archivo
        posArchivo=0;//para leer los elementos del archivo desde el primero
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProgramas = new javax.swing.JMenu();
        menuEscalarVector = new javax.swing.JMenuItem();
        menuNormaEuclideana = new javax.swing.JMenuItem();
        menuSumaVectores = new javax.swing.JMenuItem();
        menuProductoPunto = new javax.swing.JMenuItem();
        menuSumaMatrices = new javax.swing.JMenuItem();
        menuMultiplicacionMatrices = new javax.swing.JMenuItem();
        menuBaseOrtogonal = new javax.swing.JMenuItem();
        menuBase10ABaseX = new javax.swing.JMenuItem();
        menuBase2ABase10 = new javax.swing.JMenuItem();
        menuBase8ABase10 = new javax.swing.JMenuItem();
        menuBase8ABase2 = new javax.swing.JMenuItem();
        menuIntegracion = new javax.swing.JMenuItem();
        menuDerivacion = new javax.swing.JMenuItem();
        menuLagrange = new javax.swing.JMenuItem();
        menuGaussJordan = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuEuler = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ANÁLISIS NUMÉRICO");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caratula.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 1, -1, 500));

        menuProgramas.setText("Menú");
        menuProgramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProgramasActionPerformed(evt);
            }
        });

        menuEscalarVector.setText("Multiplicaciónde un escalar por un vector");
        menuEscalarVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEscalarVectorActionPerformed(evt);
            }
        });
        menuProgramas.add(menuEscalarVector);

        menuNormaEuclideana.setText("Norma Euclideana");
        menuNormaEuclideana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNormaEuclideanaActionPerformed(evt);
            }
        });
        menuProgramas.add(menuNormaEuclideana);

        menuSumaVectores.setText("Suma de vectores");
        menuSumaVectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSumaVectoresActionPerformed(evt);
            }
        });
        menuProgramas.add(menuSumaVectores);

        menuProductoPunto.setText("Producto punto entre vectores");
        menuProductoPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductoPuntoActionPerformed(evt);
            }
        });
        menuProgramas.add(menuProductoPunto);

        menuSumaMatrices.setText("Suma de matrices");
        menuSumaMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSumaMatricesActionPerformed(evt);
            }
        });
        menuProgramas.add(menuSumaMatrices);

        menuMultiplicacionMatrices.setText("Multiplicación de matrices");
        menuMultiplicacionMatrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMultiplicacionMatricesActionPerformed(evt);
            }
        });
        menuProgramas.add(menuMultiplicacionMatrices);

        menuBaseOrtogonal.setText("Base ortogonal en R2");
        menuBaseOrtogonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBaseOrtogonalActionPerformed(evt);
            }
        });
        menuProgramas.add(menuBaseOrtogonal);

        menuBase10ABaseX.setText("Transformar decimal a base x (2<=x<=16)");
        menuBase10ABaseX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBase10ABaseXActionPerformed(evt);
            }
        });
        menuProgramas.add(menuBase10ABaseX);

        menuBase2ABase10.setText("Tranformar binario a decimal");
        menuBase2ABase10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBase2ABase10ActionPerformed(evt);
            }
        });
        menuProgramas.add(menuBase2ABase10);

        menuBase8ABase10.setText("Tranformar octal a decimal");
        menuBase8ABase10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBase8ABase10ActionPerformed(evt);
            }
        });
        menuProgramas.add(menuBase8ABase10);

        menuBase8ABase2.setText("Tranformar octal a binario");
        menuBase8ABase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBase8ABase2ActionPerformed(evt);
            }
        });
        menuProgramas.add(menuBase8ABase2);

        menuIntegracion.setText("Integración numérica");
        menuIntegracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIntegracionActionPerformed(evt);
            }
        });
        menuProgramas.add(menuIntegracion);

        menuDerivacion.setText("Derivación numérica");
        menuDerivacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDerivacionActionPerformed(evt);
            }
        });
        menuProgramas.add(menuDerivacion);

        menuLagrange.setText("Interpolación de Lagrange");
        menuLagrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLagrangeActionPerformed(evt);
            }
        });
        menuProgramas.add(menuLagrange);

        menuGaussJordan.setText("Gauss - Jordan");
        menuGaussJordan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGaussJordanActionPerformed(evt);
            }
        });
        menuProgramas.add(menuGaussJordan);

        jMenuItem1.setText("Interpolación Splines");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuProgramas.add(jMenuItem1);

        menuEuler.setText("Método de Euler");
        menuEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEulerActionPerformed(evt);
            }
        });
        menuProgramas.add(menuEuler);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuProgramas.add(menuSalir);

        jMenuBar1.add(menuProgramas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
    dispose();
}//GEN-LAST:event_menuSalirActionPerformed

private void menuEscalarVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEscalarVectorActionPerformed
    EscalarVector zzz=new EscalarVector();
    zzz.setVisible(true);
    dispose();
}//GEN-LAST:event_menuEscalarVectorActionPerformed

private void menuNormaEuclideanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNormaEuclideanaActionPerformed
    NormaEuclideana zzz=new NormaEuclideana();
    zzz.setVisible(true);
    dispose();
}//GEN-LAST:event_menuNormaEuclideanaActionPerformed

private void menuProgramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProgramasActionPerformed

}//GEN-LAST:event_menuProgramasActionPerformed

private void menuSumaVectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSumaVectoresActionPerformed
    SumaVectores zzz=new SumaVectores();
    zzz.setVisible(true);
    dispose();
}//GEN-LAST:event_menuSumaVectoresActionPerformed

private void menuProductoPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductoPuntoActionPerformed
    ProductoPunto zzz=new ProductoPunto();
    zzz.setVisible(true);
    dispose();
}//GEN-LAST:event_menuProductoPuntoActionPerformed

private void menuSumaMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSumaMatricesActionPerformed
    SumaMatrices zzz=new SumaMatrices();
    zzz.setVisible(true);
    dispose();
}//GEN-LAST:event_menuSumaMatricesActionPerformed

private void menuMultiplicacionMatricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMultiplicacionMatricesActionPerformed
    MultiplicacionMatrices zzz=new MultiplicacionMatrices();
    zzz.setVisible(true);
}//GEN-LAST:event_menuMultiplicacionMatricesActionPerformed

private void menuBaseOrtogonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBaseOrtogonalActionPerformed
    BaseOrtogonalR2 zzz=new BaseOrtogonalR2();
    zzz.setVisible(true);
    dispose();
}//GEN-LAST:event_menuBaseOrtogonalActionPerformed

private void menuBase10ABaseXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBase10ABaseXActionPerformed
    Base10ABaseX zzz=new Base10ABaseX();
    zzz.setVisible(true);
    dispose();
}//GEN-LAST:event_menuBase10ABaseXActionPerformed

private void menuBase2ABase10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBase2ABase10ActionPerformed
    Base2ABase10 zzz=new Base2ABase10();
    zzz.setVisible(true);
    dispose();
}//GEN-LAST:event_menuBase2ABase10ActionPerformed

private void menuBase8ABase10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBase8ABase10ActionPerformed
    Base8ABase10 zzz=new Base8ABase10();
    zzz.setVisible(true);
    dispose();
}//GEN-LAST:event_menuBase8ABase10ActionPerformed

private void menuBase8ABase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBase8ABase2ActionPerformed
    Base8ABase2 zzz=new Base8ABase2();
    zzz.setVisible(true);
    dispose();
}//GEN-LAST:event_menuBase8ABase2ActionPerformed

private void menuIntegracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIntegracionActionPerformed
    Integracion zzz=new Integracion();
    zzz.setVisible(true);
    dispose();
}//GEN-LAST:event_menuIntegracionActionPerformed

    private void menuDerivacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDerivacionActionPerformed
        // TODO add your handling code here:
        Derivacion zzz=new Derivacion();
        zzz.setVisible(true);
    }//GEN-LAST:event_menuDerivacionActionPerformed

    private void menuLagrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLagrangeActionPerformed
        // TODO add your handling code here:
        InterpolacionLagrange zzz=new InterpolacionLagrange();
        zzz.setVisible(true);
    }//GEN-LAST:event_menuLagrangeActionPerformed

    private void menuGaussJordanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGaussJordanActionPerformed
        // TODO add your handling code here:
        EliminacionGausiana zzz=new EliminacionGausiana();
        zzz.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuGaussJordanActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         INTERPOLACION_DE_SPLINES_CUBICOS zzz=new INTERPOLACION_DE_SPLINES_CUBICOS();
        zzz.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEulerActionPerformed
       Euler zzz=new Euler();
        zzz.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuEulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuBase10ABaseX;
    private javax.swing.JMenuItem menuBase2ABase10;
    private javax.swing.JMenuItem menuBase8ABase10;
    private javax.swing.JMenuItem menuBase8ABase2;
    private javax.swing.JMenuItem menuBaseOrtogonal;
    private javax.swing.JMenuItem menuDerivacion;
    private javax.swing.JMenuItem menuEscalarVector;
    private javax.swing.JMenuItem menuEuler;
    private javax.swing.JMenuItem menuGaussJordan;
    private javax.swing.JMenuItem menuIntegracion;
    private javax.swing.JMenuItem menuLagrange;
    private javax.swing.JMenuItem menuMultiplicacionMatrices;
    private javax.swing.JMenuItem menuNormaEuclideana;
    private javax.swing.JMenuItem menuProductoPunto;
    private javax.swing.JMenu menuProgramas;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuSumaMatrices;
    private javax.swing.JMenuItem menuSumaVectores;
    // End of variables declaration//GEN-END:variables
}
