/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EscalarVector.java
 *
 * Created on 19/04/2013, 11:29:18 AM
 */
package analisisNumerico;

import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class SumaVectores extends javax.swing.JFrame {

    /** Creates new form EscalarVector */
    public SumaVectores() {
        initComponents();
        setLocationRelativeTo(null);
    }
    double vector1[],vector2[],resultado[];
    int tam1=-1,tam2=-1;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textVector1 = new javax.swing.JTextArea();
        botonCalcular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textResultado = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textVector2 = new javax.swing.JTextArea();
        botonLeerArchivo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Suma de vectores");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Vector 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, -1));

        jLabel3.setText("Ingrese los elementos de los vectores en una sola linea y separados por espacios; o genere vectores aleatorios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, 779, -1));

        botonGenerar.setText("Generar vectores aleatorios");
        botonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 278, 234, -1));

        textVector1.setColumns(20);
        textVector1.setRows(5);
        jScrollPane1.setViewportView(textVector1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, 812, 50));

        botonCalcular.setText("Calcular");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 278, -1, -1));

        textResultado.setColumns(20);
        textResultado.setEditable(false);
        textResultado.setRows(5);
        jScrollPane2.setViewportView(textResultado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 337, 822, 52));

        jLabel4.setText("Resultado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 312, -1, -1));

        jLabel5.setText("Vector 2:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, -1, -1));

        textVector2.setColumns(20);
        textVector2.setRows(5);
        jScrollPane3.setViewportView(textVector2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 201, 822, 50));

        botonLeerArchivo.setText("Leer datos del archivo");
        botonLeerArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLeerArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(botonLeerArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 278, -1, -1));

        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        jButton1.setForeground(new java.awt.Color(51, 0, 255));
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void botonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarActionPerformed
    try{
        String n1;
        n1=JOptionPane.showInputDialog(null,"Ingrese el tamaño de los vectores","",3);
        try{
            tam1=Integer.parseInt(n1);
        }catch(Exception ex){
            Metodos.error(ex);
        }
    }catch(Exception ex){
        Metodos.error(ex);
    }
    if(tam1>=1){
        tam2=tam1;
        vector1=new double[tam1];
        vector2=new double[tam2];
        vector1=Metodos.llenarVectorAleatorio(tam1);
        vector2=Metodos.llenarVectorAleatorio(tam2);
        Metodos.imprimirVector(vector1,textVector1);
        Metodos.imprimirVector(vector2,textVector2);
        resultado=Metodos.sumaVectores(vector1,vector2);
        Metodos.imprimirVector(resultado,textResultado);
    }
}//GEN-LAST:event_botonGenerarActionPerformed

private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
    Metodos.validarTextArea(textVector1);
    Metodos.validarTextArea(textVector2);
    String texto1=textVector1.getText();
    String texto2=textVector2.getText();
    if(Metodos.validarVector(texto1)&&textVector1.getLineCount()==1
            &&Metodos.validarVector(texto2)&&textVector2.getLineCount()==1){
        if(Metodos.contarElementos(texto1)==Metodos.contarElementos(texto2)){
            try{
                vector1=Metodos.leerVector(texto1);
                vector2=Metodos.leerVector(texto2);
                resultado=Metodos.sumaVectores(vector1,vector2);
                Metodos.imprimirVector(resultado,textResultado);
            }catch(Exception ex){
                Metodos.error(ex);
            }
        }else Metodos.error("Los vectores deben tener el mismo número de elementos");
    }else Metodos.error("Los datos ingresados no corresponden a vectores");
}//GEN-LAST:event_botonCalcularActionPerformed

    private void botonLeerArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLeerArchivoActionPerformed
        if(Inicio.vecArchivo!=null){
        try{
        String n1;
        n1=JOptionPane.showInputDialog(null,"Ingrese el tamaño de los vectores","",3);
        try{
            tam1=Integer.parseInt(n1);
        }catch(Exception ex){
            Metodos.error(ex);
        }
    }catch(Exception ex){
        Metodos.error(ex);
    }
    if(tam1>=1){
        tam2=tam1;
        vector1=new double[tam1];
        vector2=new double[tam2];
        vector1=Metodos.llenarVectorArchivo(tam1);
        vector2=Metodos.llenarVectorArchivo(tam2);
        Metodos.imprimirVector(vector1,textVector1);
        Metodos.imprimirVector(vector2,textVector2);
        resultado=Metodos.sumaVectores(vector1,vector2);
        Metodos.imprimirVector(resultado,textResultado);
    }
        }else Metodos.errorArchivo();
    }//GEN-LAST:event_botonLeerArchivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicio rr = new Inicio();
        rr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonGenerar;
    private javax.swing.JButton botonLeerArchivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea textResultado;
    private javax.swing.JTextArea textVector1;
    private javax.swing.JTextArea textVector2;
    // End of variables declaration//GEN-END:variables

}
