/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EliminarUbicaciones.java
 *
 * Created on 09/07/2011, 09:01:27 PM
 */

package interfazGraficaEliminar;

import excepciones.FachadaException;
import fachadas.ListadoRutas;
import fachadas.ListadoUbicaciones;
import interfazGraficaAgregar.AgregarRutas;
import java.util.Vector;
import javax.swing.JOptionPane;
import objetoProyecto.Ubicacion;

/**
 *
 * @author Gustavo
 */
public class EliminarUbicaciones extends javax.swing.JFrame {

    /** Creates new form EliminarUbicaciones */
    public EliminarUbicaciones() {
        initComponents();
        setLocationRelativeTo(null);
    }
private Ubicacion buscado=new Ubicacion();
private ListadoUbicaciones listaUbicaciones=new ListadoUbicaciones();
private ListadoRutas listaRutas=new ListadoRutas();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        nombreUbicacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cooperativa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ELIMINAR UBICACIONES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 11, -1, -1));

        jLabel2.setText("Código ubicacón:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 47, -1, -1));
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 44, 107, -1));

        jLabel3.setText("Nombre ubicación:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 99, -1, -1));

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 43, -1, -1));

        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 143, -1, -1));

        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 143, -1, -1));

        nombreUbicacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(nombreUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 99, 107, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        nombreUbicacion.setText("");
        buscado=null;
        if(!codigo.getText().equals("")){
            Ubicacion ubicacion=new Ubicacion();
            ubicacion.setCodigoUbicacon(codigo.getText());
            try{
                buscado=listaUbicaciones.obten(ubicacion);
            }catch(FachadaException fe){
                JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
            }
            if(buscado!=null){
                nombreUbicacion.setText(buscado.getNombreUbicacion());
            } else{
                JOptionPane.showMessageDialog(null,"La ubicación no existe");
            }
        } else{
            JOptionPane.showMessageDialog(null,"Ingrese el código de la ubicación");
        }
}//GEN-LAST:event_buscarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        AgregarRutas me=new AgregarRutas();
        dispose();
        me.setVisible(true);
}//GEN-LAST:event_cancelarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        if(buscado!=null){
            Vector lista1=new Vector();
                try{
                lista1=listaRutas.consultaLugarSalida(buscado.getCodigoUbicacon());
                }catch(FachadaException fe){
                    JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
                }
            Vector lista2=new Vector();
                try{
                lista2=listaRutas.consultaLugarLlegada(buscado.getCodigoUbicacon());
                }catch(FachadaException fe){
                    JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
                }
            if(lista1.isEmpty()&&lista2.isEmpty()){
            try {
                listaUbicaciones.elimina(buscado);
                JOptionPane.showMessageDialog(null,"Ubicación eliminada con éxito");
                AgregarRutas me=new AgregarRutas();
        dispose();
        me.setVisible(true);
            } catch (FachadaException fe) {
                JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
            }
        }
 else{
                JOptionPane.showMessageDialog(null, "Error: La ubiación es utilizada en una ruta");
 }
        }
        else{
            JOptionPane.showMessageDialog(null,"No se encotró la ubicación");
         }
        
    }//GEN-LAST:event_eliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nombreUbicacion;
    // End of variables declaration//GEN-END:variables

}
