/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EliminarUnidades.java
 *
 * Created on 09/07/2011, 11:24:21 PM
 */

package interfazGraficaEliminar;

import excepciones.FachadaException;
import fachadas.ListadoRutas;
import fachadas.ListadoUnidades;
import interfazGraficaAgregar.AgregarRutas;
import java.util.Vector;
import javax.swing.JOptionPane;
import objetoProyecto.Unidad;

/**
 *
 * @author Gustavo
 */
public class EliminarUnidades extends javax.swing.JFrame {

    /** Creates new form EliminarUnidades */
    public EliminarUnidades() {
        initComponents();
        setLocationRelativeTo(null);
    }
private Unidad buscado=new Unidad();
private ListadoUnidades listaUnidades=new ListadoUnidades();
private ListadoRutas listaRutas=new ListadoRutas();
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ayudante = new javax.swing.JLabel();
        matricula = new javax.swing.JLabel();
        capacidad = new javax.swing.JLabel();
        chofer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cooperativa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Ayudante:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 211, -1, -1));

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 50, -1, -1));

        jLabel3.setText("Matricula:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 94, -1, -1));

        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 278, -1, -1));

        jLabel4.setText("Capacidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 135, -1, -1));

        jLabel5.setText("Chofer:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 173, -1, -1));

        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 51, 115, -1));

        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 278, -1, -1));

        jLabel1.setText("ELIMINAR UNIDADES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 11, -1, -1));

        jLabel2.setText("Código:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 53, -1, -1));

        ayudante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(ayudante, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 180, 20));

        matricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 110, 20));

        capacidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 40, 20));

        chofer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(chofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 180, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        matricula.setText("");
        ayudante.setText("");
        capacidad.setText("");
        chofer.setText("");
        buscado=null;
        if(!codigo.getText().equals("")){
            Unidad unidad=new Unidad();
            unidad.setCodigoUnidad(codigo.getText());
            try{
                buscado=listaUnidades.obten(unidad);
            }catch(FachadaException fe){
                JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
            }
            if(buscado!=null){
                matricula.setText(buscado.getMatricula());
                capacidad.setText(String.valueOf(buscado.getCapacidadUnidad()));
                chofer.setText(buscado.getChofer());
                ayudante.setText(buscado.getAyudante());
            } else{
                JOptionPane.showMessageDialog(null,"La unidad no existe");
                }
        } else{
            JOptionPane.showMessageDialog(null,"Ingrese el código de la unidad");
        }
}//GEN-LAST:event_buscarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
            if(buscado!=null){
                Vector lista=new Vector();
                try{
                lista=listaRutas.consultaUnidadRuta(buscado.getCodigoUnidad());
                }catch(FachadaException fe){
                    JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
                }
                if(lista.isEmpty()){
               try {
                listaUnidades.elimina(buscado);
                JOptionPane.showMessageDialog(null,"Unidad eliminada con éxito");
                AgregarRutas me=new AgregarRutas();
        dispose();
        me.setVisible(true);
            } catch (FachadaException fe) {
                JOptionPane.showMessageDialog(null,"Error: " + fe.getMessage());
            }
            }
 else{
                    JOptionPane.showMessageDialog(null, "Error: La unidad está siendo utilizada en una ruta");
 }
    }
            else{
            JOptionPane.showMessageDialog(null,"No se encotró la unidad");
         }
}//GEN-LAST:event_eliminarActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_codigoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        AgregarRutas me=new AgregarRutas();
        dispose();
        me.setVisible(true);
}//GEN-LAST:event_cancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayudante;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel capacidad;
    private javax.swing.JLabel chofer;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel matricula;
    // End of variables declaration//GEN-END:variables

}
