/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on 05/07/2011, 11:58:28 AM
 */

package interfazGrafica;


import interfazGraficaAgregar.AgregarBoletos;
import interfazGraficaModificar.ModificarClientes;
import interfazGraficaAgregar.AgregarClientes;
import interfazGraficaAgregar.AgregarRutas;
import interfazGraficaEliminar.EliminarClientes;
import interfazGraficaEliminar.EliminarRutas;
import interfazGraficaModificar.ModificarRutas;
import interfazGraficaTablas.TablaBoletos;
import interfazGraficaTablas.TablaClientes;
import interfazGraficaTablas.TablaRutas;

/**
 *
 * @author Gustavo
 */

public class Menu extends javax.swing.JFrame {

    /** Creates new form Menu */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        agrClientes = new javax.swing.JMenuItem();
        modClientes = new javax.swing.JMenuItem();
        eliClientes = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        agrRuta = new javax.swing.JMenuItem();
        modRuta = new javax.swing.JMenuItem();
        eliRuta = new javax.swing.JMenuItem();
        venderBoleto = new javax.swing.JMenuItem();
        verBoleto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        botonSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        conClientes = new javax.swing.JMenuItem();
        conRutas = new javax.swing.JMenuItem();
        conBoletos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cooperativa");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("BIENVENIDO\n\n\n");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 70));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("COOPERATIVA DE TRANSPORTE TERRESTRE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2805080862_98feff139b_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 480, 420));

        jMenuBar1.setForeground(new java.awt.Color(153, 51, 255));

        jMenu1.setForeground(new java.awt.Color(0, 51, 255));
        jMenu1.setText("Cooperativa");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenu3.setText("Cliente");

        agrClientes.setText("Agregar");
        agrClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agrClientesActionPerformed(evt);
            }
        });
        jMenu3.add(agrClientes);

        modClientes.setText("Modificar");
        modClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modClientesActionPerformed(evt);
            }
        });
        jMenu3.add(modClientes);

        eliClientes.setText("Eliminar");
        eliClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliClientesActionPerformed(evt);
            }
        });
        jMenu3.add(eliClientes);

        jMenu1.add(jMenu3);

        jMenu6.setText("Ruta");

        agrRuta.setText("Agregar");
        agrRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agrRutaActionPerformed(evt);
            }
        });
        jMenu6.add(agrRuta);

        modRuta.setText("Modificar");
        modRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modRutaActionPerformed(evt);
            }
        });
        jMenu6.add(modRuta);

        eliRuta.setText("Eliminar");
        eliRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliRutaActionPerformed(evt);
            }
        });
        jMenu6.add(eliRuta);

        jMenu1.add(jMenu6);

        venderBoleto.setText("Vender boleto");
        venderBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderBoletoActionPerformed(evt);
            }
        });
        jMenu1.add(venderBoleto);

        verBoleto.setText("Ver boleto");
        verBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBoletoActionPerformed(evt);
            }
        });
        jMenu1.add(verBoleto);
        jMenu1.add(jSeparator2);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jMenu1.add(botonSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 204));
        jMenu2.setText("Consultas");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        conClientes.setText("Clientes");
        conClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conClientesActionPerformed(evt);
            }
        });
        jMenu2.add(conClientes);

        conRutas.setText("Rutas");
        conRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conRutasActionPerformed(evt);
            }
        });
        jMenu2.add(conRutas);

        conBoletos.setText("Boletos vendidos");
        conBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conBoletosActionPerformed(evt);
            }
        });
        jMenu2.add(conBoletos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agrClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agrClientesActionPerformed
        // TODO add your handling code here:
        AgregarClientes cl=new AgregarClientes();
        cl.setVisible(true);
        dispose();
    }//GEN-LAST:event_agrClientesActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void modClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modClientesActionPerformed
        // TODO add your handling code here:
        
        ModificarClientes mc=new ModificarClientes();
        mc.setVisible(true);
        dispose();
    }//GEN-LAST:event_modClientesActionPerformed

    private void eliClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliClientesActionPerformed
        // TODO add your handling code here:
        EliminarClientes el=new EliminarClientes();
        dispose();
        el.setVisible(true);
    }//GEN-LAST:event_eliClientesActionPerformed

    private void conClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conClientesActionPerformed
        // TODO add your handling code here:
        TablaClientes ta=new TablaClientes();
        dispose();
        ta.setVisible(true);
    }//GEN-LAST:event_conClientesActionPerformed

    private void venderBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderBoletoActionPerformed
        // TODO add your handling code here:
        AgregarBoletos ag=new AgregarBoletos();
        dispose();
        ag.setVisible(true);
    }//GEN-LAST:event_venderBoletoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void agrRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agrRutaActionPerformed
        // TODO add your handling code here:
        AgregarRutas ru=new AgregarRutas();
        dispose();
        ru.setVisible(true);
    }//GEN-LAST:event_agrRutaActionPerformed

    private void modRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modRutaActionPerformed
        // TODO add your handling code here:
        ModificarRutas mo=new ModificarRutas();
        dispose();
        mo.setVisible(true);
    }//GEN-LAST:event_modRutaActionPerformed

    private void eliRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliRutaActionPerformed
        // TODO add your handling code here:
        EliminarRutas el=new EliminarRutas();
        dispose();
        el.setVisible(true);
    }//GEN-LAST:event_eliRutaActionPerformed

    private void conRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conRutasActionPerformed
        // TODO add your handling code here:
        TablaRutas ta=new TablaRutas();
        dispose();
        ta.setVisible(true);
    }//GEN-LAST:event_conRutasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void conBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conBoletosActionPerformed
        // TODO add your handling code here:
        TablaBoletos ta=new TablaBoletos();
        dispose();
        ta.setVisible(true);
    }//GEN-LAST:event_conBoletosActionPerformed

    private void verBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBoletoActionPerformed
        // TODO add your handling code here:
        BoletoFinal bo=new BoletoFinal();
        dispose();
        bo.setVisible(true);
    }//GEN-LAST:event_verBoletoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agrClientes;
    private javax.swing.JMenuItem agrRuta;
    private javax.swing.JMenuItem botonSalir;
    private javax.swing.JMenuItem conBoletos;
    private javax.swing.JMenuItem conClientes;
    private javax.swing.JMenuItem conRutas;
    private javax.swing.JMenuItem eliClientes;
    private javax.swing.JMenuItem eliRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem modClientes;
    private javax.swing.JMenuItem modRuta;
    private javax.swing.JMenuItem venderBoleto;
    private javax.swing.JMenuItem verBoleto;
    // End of variables declaration//GEN-END:variables

}
